
export const ADMIN_REGISTER_REQUEST='ADMIN_REGISTER_REQUEST'
export const ADMIN_REGISTER_SUCESS='ADMIN_REGISTER_SUCESS'
export const ADMIN_REGISTER_FAIL='ADMIN_REGISTER_FAIL'

export const ADMIN_LOGIN_REQUEST='ADMIN_LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCESS='ADMIN_LOGIN_SUCESS'
export const ADMIN_LOGIN_FAIL='ADMIN_LOGIN_FAIL'
