export const COMPLAINTS_LIST_REQUEST='COMPLAINTS_LIST_REQUEST';
export const COMPLAINTS_LIST_SUCESS='COMPLAINTS_LIST_SUCESS';
export const COMPLAINTS_LIST_FAIL='COMPLAINTS_LIST_FAIL';

export const COMPLAINTS_ADD_REQUEST='COMPLAINTS_ADD_REQUEST';
export const COMPLAINTS_ADD_SUCESS='COMPLAINTS_ADD_SUCESS';
export const COMPLAINTS_ADD_FAIL='COMPLAINTS_ADD_FAIL';
