export const ADD_NOTICE_REQUEST='ADD_NOTICE_REQUEST'
export const ADD_NOTICE_SUCESS='ADD_NOTICE_SUCESS'
export const ADD_NOTICE_FAIL='ADD_NOTICE_FAIL'

export const GET_NOTICE_REQUEST='GET_NOTICE_REQUEST'
export const GET_NOTICE_SUCESS='GET_NOTICE_SUCESS'
export const GET_NOTICE_FAIL='GET_NOTICE_FAIL'