export const SOCIETY_CREATE_REQUEST='SOCIETY_CREATE_REQUEST'
export const SOCIETY_CREATE_SUCESS='SOCIETY_CREATE_SUCESS'
export const SOCIETY_CREATE_FAIL='SOCIETY_CREATE_FAIL'


export const SOCIETY_LIST_REQUEST='SOCIETY_LIST_REQUEST'
export const SOCIETY_LIST_SUCESS='SOCIETY_LIST_SUCESS'
export const SOCIETY_LIST_FAIL='SOCIETY_LIST_FAIL'


export const SOCIETY_VIEW_REQUEST='SOCIETY_VIEW_REQUEST'
export const SOCIETY_VIEW_SUCESS='SOCIETY_VIEW_SUCESS'
export const SOCIETY_VIEW_FAIL='SOCIETY_VIEW_FAIL'

export const SOCIETY_DETAILS_REQUEST='SOCIETY_DETAILS_REQUEST'
export const SOCIETY_DETAILS_SUCESS='SOCIETY_DETAILS_SUCESS'
export const SOCIETY_DETAILS_FAIL='SOCIETY_DETAILS_FAIL'
